/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BookListItem {
        /**
          * The bookData object
         */
        "book": string;
    }
}
declare global {
    interface HTMLBookListItemElement extends Components.BookListItem, HTMLStencilElement {
    }
    var HTMLBookListItemElement: {
        prototype: HTMLBookListItemElement;
        new (): HTMLBookListItemElement;
    };
    interface HTMLElementTagNameMap {
        "book-list-item": HTMLBookListItemElement;
    }
}
declare namespace LocalJSX {
    interface BookListItem {
        /**
          * The bookData object
         */
        "book"?: string;
    }
    interface IntrinsicElements {
        "book-list-item": BookListItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "book-list-item": LocalJSX.BookListItem & JSXBase.HTMLAttributes<HTMLBookListItemElement>;
        }
    }
}
